### ISSUE TITLE
Typescript error when upgrading from v6 to v7

### ISSUE THREAD

**Issue by root-io** [pnpm/pnpm#4973]
### pnpm version:

v7.5.0

### Code to reproduce the issue:

`express` v4.18.1
Please note I do NOT use the package `@types/express`

src/foo/controllers.ts:
```typescript
import { Request, Response } from "express";

export async function upload(
  request: Request,
  response: Response
): Promise<Response> {
  return response.sendStatus(200);
}
```

src/foo/routes.ts:
```typescript
import express from "express";

const router = express.Router();

router.post(
  "/myRoute",
  (request, response, next) => { // the types here are correctly recognized in VScode
...
}
```

### Expected behavior:

No error, it is working with v6.32.25

### Actual behavior:

```shell
#14 0.444 > @foo/bar@1.0.0 build /app
#14 0.444 > tsc
#14 0.444
#14 9.651 src/foo/controllers.ts(1,35): error TS7016: Could not find a declaration file for module 'express'. '/app/node_modules/.pnpm/express@4.18.1/node_modules/express/index.js' implicitly has an 'any' type.
#14 9.651   If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
#14 9.651 src/foo/routes.ts(1,21): error TS7016: Could not find a declaration file for module 'express'. '/app/node_modules/.pnpm/express@4.18.1/node_modules/express/index.js' implicitly has an 'any' type.
#14 9.651   If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
#14 9.652 src/foo/routes.ts(15,4): error TS7006: Parameter 'request' implicitly has an 'any' type.
#14 9.652 src/foo/routes.ts(15,13): error TS7006: Parameter 'response' implicitly has an 'any' type.
#14 9.652 src/foo/routes.ts(15,23): error TS7006: Parameter 'next' implicitly has an 'any' type.
#14 9.652 src/foo/routes.ts(37,4): error TS7006: Parameter 'request' implicitly has an 'any' type.
#14 9.652 src/foo/routes.ts(37,13): error TS7006: Parameter 'response' implicitly has an 'any' type.
#14 9.652 src/foo/routes.ts(37,23): error TS7006: Parameter 'next' implicitly has an 'any' type.
#14 9.653 src/express.ts(1,67): error TS7016: Could not find a declaration file for module 'express'. '/app/node_modules/.pnpm/express@4.18.1/node_modules/express/index.js' implicitly has an 'any' type.
#14 9.653   If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
#14 9.653 src/express.ts(40,20): error TS7006: Parameter '_' implicitly has an 'any' type.
#14 9.653 src/express.ts(40,23): error TS7006: Parameter 'res' implicitly has an 'any' type.
#14 9.653 src/robots/controllers.ts(1,35): error TS7016: Could not find a declaration file for module 'express'. '/app/node_modules/.pnpm/express@4.18.1/node_modules/express/index.js' implicitly has an 'any' type.
#14 9.653   If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
#14 9.653 src/bar/routes.ts(1,21): error TS7016: Could not find a declaration file for module 'express'. '/app/node_modules/.pnpm/express@4.18.1/node_modules/express/index.js' implicitly has an 'any' type.
#14 9.653   If the 'express' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express'
#14 9.704  ELIFECYCLE  Command failed with exit code 2.
------
executor failed running [/bin/sh -c pnpm run build]: exit code: 1
make: *** [build] Error 1
```

### Additional information:

 - `node -v` prints: v16.15.1
 - Windows, macOS, or Linux?: Linux
 - tsconfig:
 
 ```javascript
{
  "compilerOptions": {
    "target": "ES2021",
    "module": "commonjs",
    "outDir": "./build",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "typeRoots": [
      "src/types",
      "node_modules/@types"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "src/jest",
    "src/**/*.test.ts"
  ]
}
 ```
