### ISSUE TITLE
Nested dependencies in some cases seem not properly resolved

### ISSUE THREAD

**Issue by vajahath** [pnpm/pnpm#6165]
### Code to reproduce the issue:
The same is also [asked on stackoverflow](https://stackoverflow.com/q/75533096/3370568).

The issue is reproduced with a fresh angular project
```sh
npm i -g @angular/cli
ng new pnpm-project --skip-install # create new project
cd pnpm-project
ng config cli.packageManager pnpm
ng generate environments

pnpm install
pnpm build # Working.

# Now and @angular/fire
ng add @angular/fire
ng build # Error
```
Error:
```
./node_modules/.pnpm/rxfire@6.0.3_firebase@9.17.1+rxjs@7.8.0/node_modules/rxfire/firestore/index.esm.js:137:40-53
Error: export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib' (possible exports: __assign, __asyncDelegator, __asyncGenerator, __asyncValues, __await, __awaiter, __classPrivateFieldGet, __classPrivateFieldSet, __createBinding, __decorate, __exportStar, __extends, __generator, __importDefault, __importStar, __makeTemplateObject, __metadata, __param, __read, __rest, __spread, __spreadArrays, __values)

```
Now the same thing with NPM - working.
```sh
rm -rf node_modules
npm install
ng build
```
### Expected behaviour:
The issue seem to be related with improper resolution of tslib version.
The proper version of tslib should be installed for each dependency.

### Actual behaviour:
dependency resolution for nested dependency seem buggy (at least in my eyes).

### How I managed to fix this?
The workaround is also added in the SO [post as answer](https://stackoverflow.com/a/75540552/3370568).

I checked the dependency requirements:

```
Angular 15
- tslib ^2.3.0
- @angular/fire 7.5.0
  - tslib ^2.0.0
  - rxfire ^6.0.0
    - tslib ^1.9.0 || ~2.1.0
```
Assuming there could me a dependency error, I done [overriding](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) the txfire>tslib version explicitly on package.json file

`package.json`
```json
{
  "overrides":{
    "rxfire>tslib": "2.1.0"
  }
}
```
This fixed the issue.

So that means, the default `"rxfire>tslib"` dependency resolution is not working properly.

### Additional information:

 - `node -v` prints: 18.14.0
 - Windows, macOS, or Linux?: MacOS, Linux

**Comment by toimc** [comment]
same here.

**Comment by GeoffreyEmerson** [comment]
I have a similar issue that breaks builds because the presence of multiple different versions of webpack will cause a compilation error. Resolving to a specific version of webpack and esbuild failed to prevent different package versions from being included in the .pnpm directory. Rolling back to pnpm@7.22.0 (which was the last version my company used) solved the issue.

**Comment by EP-coode** [comment]
same problem

**Comment by kotosha-real** [comment]
> I have a similar issue that breaks builds because the presence of multiple different versions of webpack will cause a compilation error. Resolving to a specific version of webpack and esbuild failed to prevent different package versions from being included in the .pnpm directory. Rolling back to pnpm@7.22.0 (which was the last version my company used) solved the issue.

Same here with 8.14.1, but with multiple `@codemirror/state` versions (6.2.0 and 6.4.0), which is not the direct dependency of the project. The most interesting part is that every package that has `@codemirror/state` in its dependencies specifies the acceptable range as ^6.0.0, so it is really strange that pnpm has two different versions installed, I mean why not the most recent 6.4.0? Using `overrides` solved the problem.

I then tried to reproduce it in another repo, but no luck. It's worth noting that we use pnpm monorepo and our own npm registry mirror, but I couldn't find any clue as to why this was the cause, as everything worked in 7.22.0.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

Nested dependencies in some cases seem not properly resolved with no reproduction, against pnpm 7.28.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
