### PR TITLE
fix: hoisting of dependencies after resolution stage

### LINKED ISSUE #9685: Pnpm v10.12.2 skips installing transitive dependencies
### Last pnpm version that worked

v10.12.1

### pnpm version

v10.12.2

### Code to reproduce the issue

1. Download this [project](https://github.com/vaadin/skeleton-starter-flow-spring/tree/reproduce-pnpm-install-problem)
2. `npm install -g pnpm@10.12.2`
3. `npx --yes pnpm --shamefully-hoist=true --ignore-scripts install`

Browse the directory `node_modules/@vaadin` and check that these listed transitive dependencies are not installed https://github.com/vaadin/react-components/blob/07705034a107dc824beb3902959feeecdf98f23f/packages/react-components/package.json#L28, e.g. "@vaadin/vertical-layout".

Also you can check that the imports listed in `src/main/frontend/generated/vaadin.ts` are not resolved.

### Expected behavior

Npm packages listed in `package.json` and transitive dependencies should be installed.

Pnpm v10.12.1 does install them, so if you repeat the steps above with this version, installation goes as expected.

### Actual behavior

Pnpm 10.12.2 seems to have issues only when `pnpm-lock.yaml` and `node_modules` do not exist.
Once the `pnpm-lock.yaml` is generated, I can remove `node_modules`, rerun the pnpm and then have a consistent installed packages.

### Additional information

To test the project end-to-end, you can run install pnpm globally with `npm install -g pnpm@10.12.2` (10.12.1), then run `mvn` that starts the pnpm installation, Vite compilation and Spring-Boot app in the end. 

With pnpm 10.12.1 application starts without compilation errors.

### Node.js version

22.16.0

### Operating System

macOS

### PR DESCRIPTION
**Pull request by zkochan**
close #9685

### CODE REVIEW

**Comment by LouisHaftmann** [comment]
I'm still facing the same issue as #9685 when using `pnpm fetch` ([minimal repro](https://github.com/LouisHaftmann/pnpm-issue-9685-repro))

It's missing a dependency when calling `pnpm fetch` before `pnpm install`. Works with version 10.12.1, fails with >=10.12.2

@zkochan

**Comment by zkochan** [comment]
@omar-infinitusai please create a new issue with steps to reproduce.
