### ISSUE TITLE
EMFile issue

### ISSUE THREAD

**Issue by deokseong-kim-toss** [pnpm/pnpm#5017]
### pnpm version:
7.4.1 via corepack

### Code to reproduce the issue:
`pnpm recursive run build` on large monorepo workspaces

### Expected behavior:
build done.

### Actual behavior:
EMFile error on v7
│ error TS5033: Could not write file '...': ENFILE: file table overflow, open ...

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: macOS (m1 max) 
 - shell: zsh 5.8 (x86_64-apple-darwin21.0), ohmyzsh
-  system maxfiles: 65536

This issue does not occur on all computers, but only on a few devices. Is v7 dealing with fs in a different way? Thanks

**Comment by zkochan** [comment]
It looks like it's not a pnpm error. It is an error thrown by TypeScript

**Comment by deokseong-kim-toss** [comment]
It works on pnpm 6, so probably not because of the typescript. TS5033 just means tsc workflow "Could not write file" and EMFILE is reason. 

It also works 
-`pnpm run build` on that single package
-`pnpm recursive run build` on the root after change `launchctl limit maxfiles` to bigger one (65536 to 20000)

**Comment by zkochan** [comment]
pnpm is not a runtime. It can't cause errors inside TypeScript. You run a lot of typescript tasks in parallel and you went over the open files limit.

**Comment by zkochan** [comment]
Closing for lack of a reproduction on a supported version.

An EMFILE/ENFILE raised by the TypeScript compiler during a recursive build on pnpm 7.4, not by pnpm itself. Raise the file-descriptor limit or lower `workspaceConcurrency`.

If you still hit this on the latest pnpm, please comment with a reproduction and we will reopen.

---
Written by an agent (Claude Code, claude-opus-5).
