### ISSUE TITLE
Not work with laravelmix

### ISSUE THREAD

**Issue by flihub** [pnpm/pnpm#1083]
pnpm : 1.36.1
node : 8.10
Windows 10 x64

Error: 
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

The system cannot find the path specified.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (C:\Wamp\www\test2\node_modules\.registry.npmjs.org\cross-spawn\5.1.0\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Wamp\www\test2\node_modules\.registry.npmjs.org\cross-spawn\5.1.0\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Wamp\www\test2\node_modules\.registry.npmjs.org\cross-spawn\5.1.0\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by flihub** [comment]
still not working with pnpm 2.0

**Comment by zkochan** [comment]
Could you please create a repo to reproduce the issue? I don't really know what is laravel and how to use it

**Comment by zkochan** [comment]
You should install webpack as a dependency.

That fixes the first issue but then this happens:

```
> uikit@1.0.0 watch /home/zkochan/src/test/lar
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '/home/zkochan/src/test/lar/node_modules/.registry.npmjs.org/laravel-mix/2.1.11/webpack.mix'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/zkochan/src/test/lar/node_modules/.registry.npmjs.org/laravel-mix/2.1.11/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

**Comment by puzzle9** [comment]
I don't know if you've solved it.

**Comment by flihub** [comment]
not solved...

and cant install webpack as a dependency...

pnpm install webpack@3
Already up-to-date

dependencies:
- webpack

**Comment by reneroth** [comment]
Bumping this back up to the top, maybe another kind soul found a solution for this?

**Comment by zkochan** [comment]
Seems to work with latest laravel-mix v4
if pnpm creates a flat node_modules (there seem to be some issue with babel with non-flat node_modules)

To create a flat node_modules, you can have a `.npmrc` in the root of your project, with the following content: `shamefully-flatten=true`

**Comment by flihub** [comment]
Worked with shamefully-flatten=true thank you.

**Comment by chrispage1** [comment]
@zkochan same for me. Laravel Mix v4.0.15

`shamefully-flatten=true` within `.npmrc` resolves it

**Comment by 7ammer** [comment]
While this works, it this feels like a workaround :L

**Comment by 7ammer** [comment]
Correction. It works for an existing project but not for new projects. As laravel-mix tries to install vue via npm.

**Comment by osbre** [comment]
@7ammer, here is a final solution:

```bash
echo "shamefully-flatten=true" > .npmrc
pnpm add vue-template-compiler -D
pnpm add dotenv -D
```

Now you can use it!

```bash
pnpm run watch
# or
pnpm run dev
```

**Comment by f-liva** [comment]
Still not working, why the issue was closed?

**Comment by osbre** [comment]
@f-liva What problem are you experiencing? It works for me, so maybe I can help

**Comment by f-liva** [comment]
Ok sorry it works with node v12
