### ISSUE TITLE
ESlint plugins are conflicted each other migrating to pnpm

### ISSUE THREAD

**Issue by baeharam** [pnpm/pnpm#4619]
### Code to reproduce the issue:

I tried to reproduce error using CRA, but couldn't figure out exact condition 😢 

### Expected behavior:

ESLint plugins don't conflict

### Actual behavior:

> Plugin "@typescript-eslint" was conflicted between ".eslintrc.json" and ".eslintrc.json » eslint-config-react-app#overrides[0]".
ERROR in Plugin "@typescript-eslint" was conflicted between ".eslintrc.json" and ".eslintrc.json » eslint-config-react-app#overrides[0]".

The reason why I posted this issue on pnpm is that eslint didn't conflict when we were using npm. This error was occurred migrating from npm to pnpm. I tried lots of experiments.

- Remove `node_modules` and install from scratch -> Failed
- Remove all eslint packages and re-install from scratch -> Failed

From this situation, I cannot no longer guess what is the real problem? I think installation mechanism of pnpm is related to this issue. Is there other reason that you think? Thanks for your reading.

**Comment by jasongodev** [comment]
Just to be sure, can you try a fresh pnpm install in your current project directory, BUT put a **.npmrc** file with **node-linker=hoisted** as the setting? Just to be sure it's not about node module resolution issues?

In my experience, it solves half of my problems with pnpm.

**Comment by baeharam** [comment]
@jasongodev I tried your solution.

- Put `node-linker = hoisted` to `.npmrc` file.
- Remove `node_modules`.
- Install using `pnpm i` from scratch.

Failed and other errors were occurred 😢

**Comment by jasongodev** [comment]
Will it be possible for you to share your project so we can test? Remove all business critical code, api keys, and personal identifiers.

**Comment by baeharam** [comment]
@jasongodev As I said in description, I couldn't figure out exact cause of this issue. So, I cannot reproduce this situation. Is there any guess you think?

**Comment by rdsedmundo** [comment]
Also facing this, even though I was forcing a version through `pnpm.overrides` on `package.jsn`, the paths to the final file were diffing, thus ESLint was throwing:

```
Files not linking to the same place on disk: 
/Users/work/redacted/redacted/node_modules/.pnpm/eslint-plugin-react@7.30.0_eslint@8.23.0/node_modules/eslint-plugin-react/index.js
/Users/work/redacted/redacted/node_modules/.pnpm/eslint-plugin-react@7.30.0_eslint@8.10.0/node_modules/eslint-plugin-react/index.js
```

There was a difference on the ESLint version on the folder structure that pnpm uses to name the folder.

**Comment by tyteen4a03** [comment]
+1 - same issue here.

**Comment by ggascoigne** [comment]
Same issue here, you can reproduce it on https://github.com/ggascoigne/festive-beverage/tree/d6f0e76fa5208dd923351fc3ad50f7ca72c81378. Clone it, pnpm install && pnpm lint - boom.

```
Oops! Something went wrong! :(

ESLint: 8.28.0

ESLint couldn't determine the plugin "import" uniquely.

- /Users/ggp/dev/git/fb.test/node_modules/.pnpm/eslint-plugin-import@2.26.0_a7dttoi4ai57yudycjcunoobfu/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @ggascoigne/eslint-config/ts » ./index.js » eslint-config-react-app")
- /Users/ggp/dev/git/fb.test/node_modules/.pnpm/eslint-plugin-import@2.26.0_vfrilbydaxalswvos6uuh4sxs4/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @ggascoigne/eslint-config/ts » ./index.js » ./base.js » eslint-config-airbnb-base » /Users/ggp/dev/git/fb.test/node_modules/.pnpm/eslint-config-airbnb-base@15.0.0_ktrec6dplf4now6nlbc6d67jee/node_modules/eslint-config-airbnb-base/rules/imports.js")

Please remove the "plugins" setting from either config or remove either plugin installation.
```

**Comment by dormammun** [comment]
Is there some workaround? Seems `pnpm` adds some hash to the packages and when `eslint` check packages they are not equal. 

```bash
Error: Plugin "import" was conflicted between "package.json » @packages/eslint-config-hub/.remix.js » ./.react.js » ./.base.js » plugin:import/recommended" and "package.json » @packages/eslint-config-hub/.remix.js » ./.react.js » ./.base.js » plugin:github/recommended".
```
If you debug where error is happens: `node_modules/.pnpm/@eslint+eslintrc@1.4.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs`
```js
else if (sourceValue.filePath !== targetValue.filePath) {
            console.log(targetValue.filePath)
            console.log(sourceValue.filePath)
            throw new PluginConflictError(key, [
                {
                    filePath: targetValue.filePath,
                    importerName: targetValue.importerName
                },
                {
                    filePath: sourceValue.filePath,
                    importerName: sourceValue.importerName
                }
            ]);
        }
    }
```

You will get this:
```bash
/Users/dormammun/code/random-video-chat/hub/node_modules/.pnpm/eslint-plugin-import@2.26.0/node_modules/eslint-plugin-import/lib/index.js

/Users/dormammun/code/random-video-chat/hub/node_modules/.pnpm/eslint-plugin-import@2.26.0_k6edyionkpwtvb5fzwjupgro4y/node_modules/eslint-plugin-import/lib/index.js
```

`eslint-plugin-import@2.26.0` vs `eslint-plugin-import@2.26.0_k6edyionkpwtvb5fzwjupgro4y`

**Comment by dormammun** [comment]
Fixed with:
`.npmrc`
```txt
auto-install-peers = true
```

**Comment by Amit0617** [comment]
> 

May you explain what you did there? Did you also removed node_modules and did `pnpm install`?

**Comment by nnecec** [comment]
same issue
```
Oops! Something went wrong! :(

ESLint: 8.35.0

ESLint couldn't determine the plugin "import" uniquely.

- /node_modules/.pnpm/eslint-plugin-import@2.27.5_z4t62rwba3aha3c5ltpvvca4q4/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @remix-run/eslint-config")
- /node_modules/.pnpm/eslint-plugin-import@2.27.5_ajyizmi44oc3hrc35l6ndh7p4e/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @nnecec/eslint-config/react-universal » ./react » ./typescript » ./base.js » plugin:import/recommended")

Please remove the "plugins" setting from either config or remove either plugin installation.
```

**Comment by nnecec** [comment]
> same issue
> 
> ```
> Oops! Something went wrong! :(
> 
> ESLint: 8.35.0
> 
> ESLint couldn't determine the plugin "import" uniquely.
> 
> - /node_modules/.pnpm/eslint-plugin-import@2.27.5_z4t62rwba3aha3c5ltpvvca4q4/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @remix-run/eslint-config")
> - /node_modules/.pnpm/eslint-plugin-import@2.27.5_ajyizmi44oc3hrc35l6ndh7p4e/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.js » @nnecec/eslint-config/react-universal » ./react » ./typescript » ./base.js » plugin:import/recommended")
> 
> Please remove the "plugins" setting from either config or remove either plugin installation.
> ```

auto fixed when I update pnpm to v8.0.0 😂

**Comment by baeharam** [comment]
It's already been year I posted this issue and I think this issue could be solved by **updating recent version** of pnpm 😄

**Comment by christopher-francisco** [comment]
@baeharam "recent"as in latest 7, or 8?

**Comment by vance** [comment]
Still having this issue with version 9. Multiple eslint versions causing conflict/double declaration.

<img width="400" alt="image" src="https://github.com/pnpm/pnpm/assets/145471/23e94482-9b04-476c-b92c-e550534e94f2">

```

node_modules/.pnpm/@types+eslint@7.29.0/node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
       ~~~~~~~

  node_modules/.pnpm/@types+eslint@8.56.10/node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
           ~~~~~~~
    'Prepend' was also declared here.
```

**Comment by ekottifiok** [comment]
is this issue closed? cause, I've being fighting my computer for the past 4 days because of this error
I thought it was an eslint error
please pnpm fix this error it's not fun

**Comment by theoludwig** [comment]
This issue should be reopened, it's still a problem with pnpm v9.

**Comment by ekottifiok** [comment]
i didn't notice when I commented, please can you reopen the issue
